"""002_addISBN_10

Revision ID: 04659e2c3a9a
Revises: 69a9f86e5636
Create Date: 2022-01-21 02:01:57.474589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04659e2c3a9a'
down_revision = '69a9f86e5636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ISBN_10', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'ISBN_10')
    # ### end Alembic commands ###
