"""004_addPageCountLogic

Revision ID: 2794275db297
Revises: 9cfe99e1dc90
Create Date: 2022-01-21 04:04:10.994575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2794275db297'
down_revision = '9cfe99e1dc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=13), nullable=False))
    op.add_column('books', sa.Column('pageCount', sa.Integer(), nullable=True))
    op.drop_constraint('books_ISBN_10_key', 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.drop_column('books', 'ISBN_10')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ISBN_10', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint('books_ISBN_10_key', 'books', ['ISBN_10'])
    op.drop_column('books', 'pageCount')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
