"""007_addLentHistory

Revision ID: 49a437ab5e26
Revises: 8d0f34ad9055
Create Date: 2022-01-22 03:35:35.944919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a437ab5e26'
down_revision = '8d0f34ad9055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lentHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('lentDate', sa.DateTime(), nullable=True),
    sa.Column('returnDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lentHistory')
    # ### end Alembic commands ###
