"""005_addCustomer

Revision ID: 5e0e8d9c717c
Revises: 2794275db297
Create Date: 2022-01-21 21:37:52.458331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0e8d9c717c'
down_revision = '2794275db297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('pageCount', sa.Integer(), nullable=True),
    sa.Column('isLent', sa.Boolean(), nullable=False),
    sa.Column('addDate', sa.DateTime(), nullable=True),
    sa.Column('latestLent', sa.DateTime(), nullable=True),
    sa.Column('latestReturn', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('pageCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    sa.UniqueConstraint('isbn', name='books_isbn_key')
    )
    op.drop_table('book')
    op.drop_table('customer')
    # ### end Alembic commands ###
