"""005_updateUnique

Revision ID: 8d0f34ad9055
Revises: 5e0e8d9c717c
Create Date: 2022-01-22 00:34:11.548619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0f34ad9055'
down_revision = '5e0e8d9c717c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'customer', ['email'])
    op.create_unique_constraint(None, 'customer', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('book', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
