"""008_updateIsLentField

Revision ID: 9135cdbe43a6
Revises: 49a437ab5e26
Create Date: 2022-01-29 03:37:23.848975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9135cdbe43a6'
down_revision = '49a437ab5e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'isLent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('isLent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
